Resources:
  MyEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-06b21ccaeff8cd686  # Replace with your chosen AMI ID
      KeyName: suiii
      SecurityGroups: 
        - default
