
          Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-06b21ccaeff8cd686                # Replace with your AMI ID
      KeyName: suiii         # Replace with your key pair name
      SecurityGroups:
        - default          # Replace with your security group ID
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo apt-get update -y
          sudo apt-get install -y apache2
          echo "<h1>Hello, DevOps Pipeline is set up!</h1>" > /var/www/html/index.html
          sudo systemctl start apache2
